##Imports

In [ ]:
#imports
%%capture
!pip install pymzml pyopenms pandas numpy tqdm
import pyopenms as oms
import pandas as pd
import numpy as np
from tqdm import tqdm

In [ ]:
#gets mzML files from content
#chosen from https://www.ebi.ac.uk/pride/archive/projects/PXD017211

import os
mzml_files = [f for f in os.listdir() if f.endswith(".mzML")]
mzml_files

['181011_Leaders_11_4_E01.mzML',
 '181011_Leaders_6_4_E04.mzML',
 '181011_Leaders_34_7_E01.mzML']

In [ ]:
%%capture
!apt-get -qq install -y openms

##Examining Top Features

In [ ]:
import pyopenms as oms, numpy as np, pandas as pd, glob

def quick_prominent_features(mzml, max_ms1=500, top_k=30, mz_bin=0.01):
  exp = oms.MSExperiment()
  oms.MzMLFile().load(mzml, exp)

  bins = {}
  used = 0
  for spec in exp:
    if spec.getMSLevel()!=1 or spec.size()==0:
      continue
    mzs, ints = spec.get_peaks()
    mzs = np.array(mzs); ints = np.array(ints)
    b = np.round(mzs/mz_bin).astype(int)
    for bi,inten in zip(b,ints):
      if inten > bins.get(bi,0):
        bins[bi]=float(inten)
    used+=1
    if used>=max_ms1: break

  df = pd.DataFrame({"MZ":[k*mz_bin for k in bins], "MaxIntensity":list(bins.values())})
  return df.sort_values("MaxIntensity",ascending=False).head(top_k)

for f in sorted(glob.glob("*.mzML")):
  print("\n==",f,"==")
  display(quick_prominent_features(f, max_ms1=500, top_k=20))

== 181011_Leaders_11_4_E01.mzML ==

          MZ   MaxIntensity
224   401.92  664384.187500
128   378.95  484678.156250
25    354.89  444237.343750
285   416.88  383040.593750
211   399.91  314801.906250
685   580.79  297975.531250
1380  438.83  272605.250000
303   420.82  237125.781250
50    360.82  188524.234375
783   632.82  186772.062500
360   438.84  179282.890625
347   436.82  176726.375000
1301  368.98  153899.906250
486   482.94  150285.687500
237   404.92  137732.156250
298   419.32  129252.054688
714   597.82  124777.445312
233   403.92  104734.101562
1311  376.95  101928.445312
654   562.82   98383.179688

== 181011_Leaders_34_7_E01.mzML ==

         MZ  MaxIntensity
44   401.92  72677.468750
108  580.79  57264.179688
268  416.88  45082.558594
126  632.82  41849.062500
63   438.83  41436.292969
16   372.97  39000.097656
52   416.87  35578.421875
10   360.82  33386.890625
122  615.79  28240.595703
55   420.82  27943.363281
62   438.80  25768.164062
39   399.91  24442.902344
3    354.89  18989.046875
72   460.72  18866.751953
60   436.82  18293.115234
69   442.97  15284.764648
115  597.82  14322.099609
23   376.81  13871.994141
79   499.81  13746.873047
879  376.82  13680.300781

== 181011_Leaders_6_4_E04.mzML ==

          MZ  MaxIntensity
29    354.89  1.318249e+06
425   420.82  9.311674e+05
2158  416.87  8.769820e+05
494   438.83  7.582506e+05
403   416.88  7.224408e+05
186   378.95  7.063605e+05
68    360.82  6.867121e+05
1046  580.79  6.630595e+05
483   436.82  6.395928e+05
308   399.91  6.298863e+05
511   442.75  3.803541e+05
1214  632.82  3.172872e+05
341   404.92  2.804078e+05
1163  615.79  2.756590e+05
325   401.92  2.704591e+05
2079  376.81  2.494713e+05
491   438.80  2.463298e+05
586   460.72  2.429676e+05
252   391.28  2.046599e+05
2351  578.79  1.965039e+05

In [ ]:
import glob
import pandas as pd

mzmls = sorted(glob.glob("*.mzML"))

# Get top MS1 peaks per file
top_ms1 = {}
for f in mzmls:
  df = quick_prominent_features(f, max_ms1=500, top_k=50, mz_bin=0.01)  # adjust as needed
  top_ms1[f] = df

# Example
display(top_ms1[mzmls[0]].head(20))

          MZ   MaxIntensity
224   401.92  664384.187500
128   378.95  484678.156250
25    354.89  444237.343750
285   416.88  383040.593750
211   399.91  314801.906250
685   580.79  297975.531250
1380  438.83  272605.250000
303   420.82  237125.781250
50    360.82  188524.234375
783   632.82  186772.062500
360   438.84  179282.890625
347   436.82  176726.375000
1301  368.98  153899.906250
486   482.94  150285.687500
237   404.92  137732.156250
298   419.32  129252.054688
714   597.82  124777.445312
233   403.92  104734.101562
1311  376.95  101928.445312
654   562.82   98383.179688

##Proteomics Analysis Take #1

In [1]:
%%capture
!curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
!./bin/micromamba create -y -n proteomics -c conda-forge -c bioconda msfragger philosopher

In [ ]:
!wget -q -O human_swissprot.fasta "https://rest.uniprot.org/uniprotkb/stream?query=organism_id:9606+AND+reviewed:true&format=fasta"
!ls -lh human_swissprot.fasta

-rw-r--r-- 1 root root 14M Jan 21 03:05 human_swissprot.fasta

In [ ]:
import glob
candidates = glob.glob("/root/.local/share/mamba/envs/proteomics/share/msfragger-*/MSFragger-*/MSFragger-*.jar")
msfragger_jar = sorted(candidates)[-1]
print("Using:", msfragger_jar)

Using: /root/.local/share/mamba/envs/proteomics/share/msfragger-4.2-0/MSFragger-4.2/MSFragger-4.2.jar

In [ ]:
params = """database_name = human_swissprot.fasta
num_threads = 4

# Use ppm tolerance (required to avoid precursor_mass_units=2 error)
precursor_mass_units = 1
precursor_mass_lower = -20
precursor_mass_upper = 20

fragment_mass_units = 1
fragment_mass_tolerance = 20

search_enzyme_name = Trypsin
allowed_missed_cleavage = 2
variable_mod_01 = 15.9949 M
output_report_topN = 1
"""
open("fragger.params","w").write(params)
!cat fragger.params

database_name = human_swissprot.fasta
num_threads = 4

# Use ppm tolerance (required to avoid precursor_mass_units=2 error)
precursor_mass_units = 1
precursor_mass_lower = -20
precursor_mass_upper = 20

fragment_mass_units = 1
fragment_mass_tolerance = 20

search_enzyme_name = Trypsin
allowed_missed_cleavage = 2
variable_mod_01 = 15.9949 M
output_report_topN = 1

In [ ]:
KEY = "5c6f23ef-cadb78c8-8cfcf03e-aea9baf6"
!./bin/micromamba run -n proteomics java -Xmx16G -jar "{msfragger_jar}" --key {KEY} fragger.params *.mzML

[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
MSFragger version MSFragger-4.2
Batmass-IO version 1.35.1
WARNING: A restricted method in java.lang.System has been called
WARNING: java.lang.System::load has been called by com.sun.jna.Native in an unnamed module (file:/root/.local/share/mamba/envs/proteomics/share/msfragger-4.2-0/MSFragger-4.2/MSFragger-4.2.jar)
WARNING: Use --enable-native-access=ALL-UNNAMED to avoid a warning for callers in this module
WARNING: Restricted methods will be blocked in a future release unless native access is enabled

timsdata library version timsdata-2-21-0-4
(c) University of Michigan
RawFileReader reading tool. Copyright (c) 2016 by Thermo Fisher Scientific, Inc. All rights reserved.
timdTOF .d reading tool. Copyright (c) 2022 by Bruker Daltonics GmbH & Co. KG. All rights reserved.
System OS: Linux, Architecture: amd64
Java Info: 25.0.1-internal, OpenJDK 64-Bit Server VM, Oracle Corporation
License key verified.
JVM started with 16 GB memory
Parameter 'data_type' was not supplied. Using default value: 0
Checking database...
Parameter 'num_enzyme_termini' was not supplied. Using default value: 2
Parameter 'search_enzyme_cutafter' was not supplied. Using default value: KR
Parameter 'search_enzyme_butnotafter' was not supplied. Using default value:
Parameter 'digest_min_length' was not supplied. Using default value: 7
Parameter 'digest_max_length' was not supplied. Using default value: 50
Parameter 'digest_mass_range' was not supplied. Using default value: 500.0 5000.0
Parameter 'delta_mass_exclude_ranges' was not supplied. Using default value: (-1.5, 3.5)
Parameter 'precursor_true_tolerance' was not supplied. Using default value: 20.000000
Parameter 'precursor_true_units' was not supplied. Using default value: 1
Parameter 'min_sequence_matches' was not supplied. Using default value: 2
Parameter 'remove_precursor_peak' was not supplied. Using default value: 1
Parameter 'intensity_transform' was not supplied. Using default value: 0
Parameter 'diagnostic_intensity_filter' was not supplied. Using default value: 0.000000
Parameter 'max_fragment_charge' was not supplied. Using default value: 2
Parameter 'deisotope' was not supplied. Using default value: 1
Parameter 'deneutralloss' was not supplied. Using default value: 1
Parameter 'use_topN_peaks' was not supplied. Using default value: 150
Parameter 'minimum_ratio' was not supplied. Using default value: 0.010000
Parameter 'clear_mz_range' was not supplied. Using default value: 0.0 0.0
Parameter 'minimum_peaks' was not supplied. Using default value: 15
Parameter 'min_fragments_modelling' was not supplied. Using default value: 2
Parameter 'min_matched_fragments' was not supplied. Using default value: 4
Parameter 'output_max_expect' was not supplied. Using default value: 50.000000
Parameter 'output_format' was not supplied. Using default value: pepxml
Parameter 'zero_bin_accept_expect' was not supplied. Using default value: 0.000000
Parameter 'zero_bin_mult_expect' was not supplied. Using default value: 1.000000
Parameter 'clip_nTerm_M' was not supplied. Using default value: 1
Parameter 'remove_precursor_range' was not supplied. Using default value: -1.5,1.5
Parameter 'precursor_mass_mode' was not supplied. Using default value: SELECTED
Parameter 'calibrate_mass' was not supplied. Using default value: 2
Parameter 'write_calibrated_mzml' was not supplied. Using default value: 0
Parameter 'write_mzbin_all' was not supplied. Using default value: 0
Parameter 'decoy_prefix' was not supplied. Using default value: rev_
Parameter 'use_all_mods_in_first_search' was not supplied. Using default value: 0
Parameter 'require_precursor' was not supplied. Using default value: 0
Parameter 'reuse_dia_fragment_peaks' was not supplied. Using default value: 0
Parameter 'activation_types' was not supplied. Using default value: all
Parameter 'analyzer_types' was not supplied. Using default value: all
Parameter 'fragment_ion_series' was not supplied. Using default value: b,y
Parameter 'ion_series_definitions' was not supplied. Using default value:
Parameter 'diagnostic_fragments' was not supplied. Using default value:
Checking spectral files...
181011_Leaders_6_4_E04.mzML: Scans = 55526; MS2 ITMS = false; MS2 FTMS = true; MS2 ASTMS = false; MS1 ITMS = false; Isolation sizes = [2.0]; Instrument = Q Exactive Plus
181011_Leaders_34_7_E01.mzML: Scans = 58142; MS2 ITMS = false; MS2 FTMS = true; MS2 ASTMS = false; MS1 ITMS = false; Isolation sizes = [2.0]; Instrument = Q Exactive Plus
181011_Leaders_11_4_E01.mzML: Scans = 53295; MS2 ITMS = false; MS2 FTMS = true; MS2 ASTMS = false; MS1 ITMS = false; Isolation sizes = [2.0]; Instrument = Q Exactive Plus
***********************************FIRST SEARCH************************************
Parameters:
num_threads = 4
database_name = human_swissprot.fasta
decoy_prefix = rev_
precursor_mass_lower = -20.0
precursor_mass_upper = 20.0
precursor_mass_units = 1
data_type = 0
precursor_true_tolerance = 20.0
precursor_true_units = 1
fragment_mass_tolerance = 20.0
fragment_mass_units = 1
calibrate_mass = 2
use_all_mods_in_first_search = 0
write_calibrated_mzml = 0
write_uncalibrated_mzml = 1
write_mzbin_all = 0
isotope_error = 0/1
mass_offsets = 0
use_detailed_offsets = 0
labile_search_mode = OFF
restrict_deltamass_to = all
precursor_mass_mode = SELECTED
localize_delta_mass = 0
delta_mass_exclude_ranges = (-1.5, 3.5)
fragment_ion_series = b,y
ion_series_definitions =
search_enzyme_name = Trypsin
search_enzyme_sense_1 = C
search_enzyme_cut_1 = KR
search_enzyme_nocut_1 =
allowed_missed_cleavage_1 = 2
num_enzyme_termini = 2
clip_nTerm_M = 1
allow_multiple_variable_mods_on_residue = 0
max_variable_mods_per_peptide = 3
max_variable_mods_combinations = 5000
output_format = pepxml
output_report_topN = 1
output_max_expect = 50.0
report_alternative_proteins = 0
override_charge = 0
precursor_charge_low = 2
precursor_charge_high = 3
digest_min_length = 7
digest_max_length = 50
digest_mass_range_low = 500.0
digest_mass_range_high = 5000.0
max_fragment_charge = 1
deisotope = 1
deneutralloss = 1
track_zero_topN = 0
zero_bin_accept_expect = 0.0
zero_bin_mult_expect = 1.0
minimum_peaks = 15
use_topN_peaks = 150
minIonsScoring = 2
min_matched_fragments = 4
minimum_ratio = 0.01
intensity_transform = 0
activation_types = all
analyzer_types = all
group_variable = 0
require_precursor = 0
reuse_dia_fragment_peaks = 0
remove_precursor_peak = 1
remove_precursor_range = -1.5,1.5
clear_mz_range_low = 0.0
clear_mz_range_high = 0.0
excluded_scan_list_file =
mass_diff_to_variable_mod = 0
min_sequence_matches = 2
check_spectral_files = 1
variable_mod_01 = 15.9949 M
add_Cterm_peptide = 0.0
add_Cterm_protein = 0.0
add_Nterm_peptide = 0.0
add_Nterm_protein = 0.0
Number of unique peptides
	of length 7: 145840
	of length 8: 140436
	of length 9: 139811
	of length 10: 132102
	of length 11: 125396
	of length 12: 119929
	of length 13: 116821
	of length 14: 109442
	of length 15: 103831
	of length 16: 97107
	of length 17: 90854
	of length 18: 87350
	of length 19: 85758
	of length 20: 76817
	of length 21: 73450
	of length 22: 68937
	of length 23: 64214
	of length 24: 60956
	of length 25: 57447
	of length 26: 53377
	of length 27: 50870
	of length 28: 48580
	of length 29: 44212
	of length 30: 41991
	of length 31: 39390
	of length 32: 37345
	of length 33: 34880
	of length 34: 32716
	of length 35: 29631
	of length 36: 28769
	of length 37: 26301
	of length 38: 24706
	of length 39: 22215
	of length 40: 21207
	of length 41: 19758
	of length 42: 18154
	of length 43: 15290
	of length 44: 12393
	of length 45: 9515
	of length 46: 6220
	of length 47: 3927
	of length 48: 2284
	of length 49: 1250
	of length 50: 757
In total 2522236 peptides.
Generated 3846843 modified peptides.
Number of peptides with more than 5000 modification patterns: 0
Selected fragment index width 0.10 Da.
156880900 fragments to be searched in 1 slices (1.46 GB total)
Operating on slice 1 of 1:
	Fragment index slice generated in 2.94 s
	001. 181011_Leaders_11_4_E01.mzML 7.6 s | deisotoping 0.6 s
		[progress: 53295/53295 (100%) - 17159 spectra/s] 3.1s
	002. 181011_Leaders_34_7_E01.mzML 6.9 s | deisotoping 0.2 s
		[progress: 58142/58142 (100%) - 27271 spectra/s] 2.1s
	003. 181011_Leaders_6_4_E04.mzML 6.6 s | deisotoping 0.1 s
		[progress: 55526/55526 (100%) - 34596 spectra/s] 1.6s
postprocessing 181011_Leaders_11_4_E01.mzML 0.3 s
postprocessing 181011_Leaders_34_7_E01.mzML 0.2 s
postprocessing 181011_Leaders_6_4_E04.mzML 0.1 s
***************************FIRST SEARCH DONE IN 0.868 MIN**************************

*********************MASS CALIBRATION AND PARAMETER OPTIMIZATION*******************
-----|---------------|---------------|---------------|---------------
     |  MS1   (Old)  |  MS1   (New)  |  MS2   (Old)  |  MS2   (New)
-----|---------------|---------------|---------------|---------------
 Run |  Median  MAD  |  Median  MAD  |  Median  MAD  |  Median  MAD
 001 |   0.73   1.48 |   0.01   0.69 |   0.27   2.60 |  -0.12   2.56
 002 |   0.50   1.38 |   0.04   0.74 |  -0.15   2.52 |  -0.06   2.51
 003 |  -0.72   1.44 |   0.01   0.68 |  -1.28   2.72 |  -0.11   2.71
-----|---------------|---------------|---------------|---------------
Finding the optimal parameters:
-------|-------|-------|-------|-------|-------|-------|-------|-------
  MS2  |    5  |    7  |   10  |   15  |   20  |   25  |   30  |   50
-------|-------|-------|-------|-------|-------|-------|-------|-------
 Count | skip  |  21014|  22500|  24167|  25379|  26251|  26921|  28968
-------|-------|-------|-------|-------|-------|-------|-------|-------
-------|-------|-------|-------|-------|-------|-------
 Peaks | 300_0 | 200_0 | 175_0 | 150_1 | 125_1 | 100_1
-------|-------|-------|-------|-------|-------|-------
 Count |  29110|  29096| skip rest
-------|-------|-------|-------|-------|-------|-------
-------|-------
 Int.  |    1
-------|-------
 Count |  29111
-------|-------
-------|-------
 Rm P. |    0
-------|-------
 Count |  29240
-------|-------
New fragment_mass_tolerance = 50.000000 PPM
New use_topN_peaks = 300
New minimum_ratio = 0.000000
New intensity_transform = 1
New remove_precursor_peak = 0
************MASS CALIBRATION AND PARAMETER OPTIMIZATION DONE IN 1.741 MIN*********

************************************MAIN SEARCH************************************
Parameter 'data_type' was not supplied. Using default value: 0
Checking database...
Parameter 'num_enzyme_termini' was not supplied. Using default value: 2
Parameter 'search_enzyme_cutafter' was not supplied. Using default value: KR
Parameter 'search_enzyme_butnotafter' was not supplied. Using default value:
Parameter 'digest_min_length' was not supplied. Using default value: 7
Parameter 'digest_max_length' was not supplied. Using default value: 50
Parameter 'digest_mass_range' was not supplied. Using default value: 500.0 5000.0
Parameter 'localize_delta_mass' was not supplied. Using default value: 0
Parameter 'delta_mass_exclude_ranges' was not supplied. Using default value: (-1.5, 3.5)
Parameter 'precursor_true_tolerance' was not supplied. Using default value: 20.000000
Parameter 'precursor_true_units' was not supplied. Using default value: 1
Parameter 'mass_offsets' was not supplied. Using default value: 0
Parameter 'use_detailed_offsets' was not supplied. Using default value: 0
Parameter 'labile_search_mode' was not supplied. Using default value: OFF
Parameter 'restrict_deltamass_to' was not supplied. Using default value: all
Parameter 'min_sequence_matches' was not supplied. Using default value: 2
Parameter 'remove_precursor_peak' was not supplied. Using default value: 1
Parameter 'intensity_transform' was not supplied. Using default value: 0
Parameter 'diagnostic_intensity_filter' was not supplied. Using default value: 0.000000
Parameter 'max_fragment_charge' was not supplied. Using default value: 2
Parameter 'deisotope' was not supplied. Using default value: 1
Parameter 'deneutralloss' was not supplied. Using default value: 1
Parameter 'use_topN_peaks' was not supplied. Using default value: 150
Parameter 'minimum_ratio' was not supplied. Using default value: 0.010000
Parameter 'clear_mz_range' was not supplied. Using default value: 0.0 0.0
Parameter 'isotope_error' was not supplied. Using default value: 0
Parameter 'minimum_peaks' was not supplied. Using default value: 15
Parameter 'min_fragments_modelling' was not supplied. Using default value: 2
Parameter 'min_matched_fragments' was not supplied. Using default value: 4
Parameter 'override_charge' was not supplied. Using default value: 0
Parameter 'precursor_charge' was not supplied. Using default value: 1 4
Parameter 'output_max_expect' was not supplied. Using default value: 50.000000
Parameter 'output_format' was not supplied. Using default value: pepxml
Parameter 'track_zero_topN' was not supplied. Using default value: 0
Parameter 'zero_bin_accept_expect' was not supplied. Using default value: 0.000000
Parameter 'zero_bin_mult_expect' was not supplied. Using default value: 1.000000
Parameter 'allow_multiple_variable_mods_on_residue' was not supplied. Using default value: 0
Parameter 'max_variable_mods_per_peptide' was not supplied. Using default value: 3
Parameter 'max_variable_mods_combinations' was not supplied. Using default value: 5000
Parameter 'clip_nTerm_M' was not supplied. Using default value: 1
Parameter 'remove_precursor_range' was not supplied. Using default value: -1.5,1.5
Parameter 'precursor_mass_mode' was not supplied. Using default value: SELECTED
Parameter 'report_alternative_proteins' was not supplied. Using default value: 0
Parameter 'calibrate_mass' was not supplied. Using default value: 2
Parameter 'write_calibrated_mzml' was not supplied. Using default value: 0
Parameter 'write_mzbin_all' was not supplied. Using default value: 0
Parameter 'decoy_prefix' was not supplied. Using default value: rev_
Parameter 'use_all_mods_in_first_search' was not supplied. Using default value: 0
Parameter 'group_variable' was not supplied. Using default value: 0
Parameter 'require_precursor' was not supplied. Using default value: 0
Parameter 'reuse_dia_fragment_peaks' was not supplied. Using default value: 0
Parameter 'activation_types' was not supplied. Using default value: all
Parameter 'analyzer_types' was not supplied. Using default value: all
Parameter 'fragment_ion_series' was not supplied. Using default value: b,y
Parameter 'remainder_fragment_masses' was not supplied. Using default value:
Parameter 'Y_type_masses' was not supplied. Using default value:
Parameter 'ion_series_definitions' was not supplied. Using default value:
Parameter 'diagnostic_fragments' was not supplied. Using default value:
Parameter 'mass_diff_to_variable_mod' was not supplied. Using default value: 0
Parameters:
num_threads = 4
database_name = human_swissprot.fasta
decoy_prefix = rev_
precursor_mass_lower = -20.0
precursor_mass_upper = 20.0
precursor_mass_units = 1
data_type = 0
precursor_true_tolerance = 20.0
precursor_true_units = 1
fragment_mass_tolerance = 50.0
fragment_mass_units = 1
calibrate_mass = 2
use_all_mods_in_first_search = 0
write_calibrated_mzml = 0
write_uncalibrated_mzml = 1
write_mzbin_all = 0
isotope_error = 0
mass_offsets = 0
use_detailed_offsets = 0
labile_search_mode = OFF
restrict_deltamass_to = all
precursor_mass_mode = SELECTED
localize_delta_mass = 0
delta_mass_exclude_ranges = (-1.5, 3.5)
fragment_ion_series = b,y
ion_series_definitions =
search_enzyme_name = Trypsin
search_enzyme_sense_1 = C
search_enzyme_cut_1 = KR
search_enzyme_nocut_1 =
allowed_missed_cleavage_1 = 2
num_enzyme_termini = 2
clip_nTerm_M = 1
allow_multiple_variable_mods_on_residue = 0
max_variable_mods_per_peptide = 3
max_variable_mods_combinations = 5000
output_format = pepxml
output_report_topN = 1
output_max_expect = 50.0
report_alternative_proteins = 0
override_charge = 0
precursor_charge_low = 1
precursor_charge_high = 4
digest_min_length = 7
digest_max_length = 50
digest_mass_range_low = 500.0
digest_mass_range_high = 5000.0
max_fragment_charge = 1
deisotope = 1
deneutralloss = 1
track_zero_topN = 0
zero_bin_accept_expect = 0.0
zero_bin_mult_expect = 1.0
minimum_peaks = 15
use_topN_peaks = 300
minIonsScoring = 2
min_matched_fragments = 4
minimum_ratio = 0.0
intensity_transform = 1
activation_types = all
analyzer_types = all
group_variable = 0
require_precursor = 0
reuse_dia_fragment_peaks = 0
remove_precursor_peak = 0
remove_precursor_range = -1.5,1.5
clear_mz_range_low = 0.0
clear_mz_range_high = 0.0
excluded_scan_list_file =
mass_diff_to_variable_mod = 0
min_sequence_matches = 2
check_spectral_files = 1
variable_mod_01 = 15.9949 M
add_Cterm_peptide = 0.0
add_Cterm_protein = 0.0
add_Nterm_peptide = 0.0
add_Nterm_protein = 0.0
Number of unique peptides
	of length 7: 145840
	of length 8: 140436
	of length 9: 139811
	of length 10: 132102
	of length 11: 125396
	of length 12: 119929
	of length 13: 116821
	of length 14: 109442
	of length 15: 103831
	of length 16: 97107
	of length 17: 90854
	of length 18: 87350
	of length 19: 85758
	of length 20: 76817
	of length 21: 73450
	of length 22: 68937
	of length 23: 64214
	of length 24: 60956
	of length 25: 57447
	of length 26: 53377
	of length 27: 50870
	of length 28: 48580
	of length 29: 44212
	of length 30: 41991
	of length 31: 39390
	of length 32: 37345
	of length 33: 34880
	of length 34: 32716
	of length 35: 29631
	of length 36: 28769
	of length 37: 26301
	of length 38: 24706
	of length 39: 22215
	of length 40: 21207
	of length 41: 19758
	of length 42: 18154
	of length 43: 15290
	of length 44: 12393
	of length 45: 9515
	of length 46: 6220
	of length 47: 3927
	of length 48: 2284
	of length 49: 1250
	of length 50: 757
In total 2522236 peptides.
Generated 3846843 modified peptides.
Number of peptides with more than 5000 modification patterns: 0
Selected fragment index width 0.25 Da.
156880900 fragments to be searched in 1 slices (1.46 GB total)
Operating on slice 1 of 1:
	Fragment index slice generated in 2.47 s
	001. 181011_Leaders_11_4_E01.mzBIN_calibrated 0.2 s
		[progress: 53295/53295 (100%) - 29575 spectra/s] 1.8s
	002. 181011_Leaders_34_7_E01.mzBIN_calibrated 0.2 s
		[progress: 58142/58142 (100%) - 27647 spectra/s] 2.1s
	003. 181011_Leaders_6_4_E04.mzBIN_calibrated 0.2 s
		[progress: 55526/55526 (100%) - 39492 spectra/s] 1.4s
postprocessing 181011_Leaders_11_4_E01.mzBIN_calibrated 0.7 s
postprocessing 181011_Leaders_34_7_E01.mzBIN_calibrated 0.6 s
postprocessing 181011_Leaders_6_4_E04.mzBIN_calibrated 0.6 s
***************************MAIN SEARCH DONE IN 0.243 MIN***************************

*******************************TOTAL TIME 2.851 MIN********************************

In [ ]:
!rm -rf .philosopher
!./bin/micromamba run -n proteomics philosopher workspace --init
!ls -la | head -n 50

time="03:08:07" level=info msg="Executing Workspace  v5.1.2"
time="03:08:08" level=info msg="Creating workspace"
time="03:08:08" level=info msg=Done
total 2624168
drwxr-xr-x 1 root root      4096 Jan 21 03:08 .
drwxr-xr-x 1 root root      4096 Jan 21 02:26 ..
-rw-r--r-- 1 root root 830684245 Jan 21 03:02 181011_Leaders_11_4_E01.mzML
-rw-r--r-- 1 root root  21985057 Jan 21 03:08 181011_Leaders_11_4_E01.pepXML
-rw-r--r-- 1 root root 841894108 Jan 21 03:02 181011_Leaders_34_7_E01.mzML
-rw-r--r-- 1 root root  25607761 Jan 21 03:08 181011_Leaders_34_7_E01.pepXML
-rw-r--r-- 1 root root 815947097 Jan 21 03:02 181011_Leaders_6_4_E04.mzML
-rw-r--r-- 1 root root  20793078 Jan 21 03:08 181011_Leaders_6_4_E04.pepXML
drwxr-xr-x 2 root root      4096 Jan 21 03:04 bin
drwxr-xr-x 4 root root      4096 Dec  9 14:41 .config
-rw-r--r-- 1 root root       365 Jan 21 03:05 fragger.params
-rw-r--r-- 1 root root  13665992 Jan 21 03:05 human_swissprot.fasta
-rw-r--r-- 1 root root  58253724 Jan 21 03:05 human_swissprot.fasta.1.pepindex
-rw-r--r-- 1 root root  58253425 Jan 21 03:07 human_swissprot.fasta.2.pepindex
drwxr-xr-x 2 root root      4096 Jan 21 02:58 .ipynb_checkpoints
drwxr-xr-x 2 root root      4096 Jan 21 03:08 .meta
drwxr-xr-x 1 root root      4096 Dec  9 14:42 sample_data

In [ ]:
!./bin/micromamba run -n proteomics philosopher database --annotate human_swissprot.fasta

time="03:08:08" level=info msg="Executing Database  v5.1.2"
time="03:08:08" level=info msg="Annotating the database"
time="03:08:08" level=info msg=Done

In [ ]:
!./bin/micromamba run -n proteomics philosopher peptideprophet --database human_swissprot.fasta *.pepXML

time="03:08:08" level=info msg="Executing PeptideProphet  v5.1.2"
 file 1: /content/181011_Leaders_11_4_E01.pepXML
No index list offset found. File will not be read.
WARNING: cannot open data file /content/181011_Leaders_11_4_E01.mzML in msms_run_summary tag... trying .mzXML ...
WARNING: CANNOT correct data file /content/181011_Leaders_11_4_E01.mzXML in msms_run_summary tag...
No index list offset found. File will not be read.
WARNING: cannot open data file /content/181011_Leaders_11_4_E01.mzML in msms_run_summary tag... trying .mzXML ...
WARNING: CANNOT correct data file /content/181011_Leaders_11_4_E01.mzXML in msms_run_summary tag...
 processed altogether 22906 results
INFO: Results written to file: /content/interact-181011_Leaders_11_4_E01.pep.xml
 file 1: /content/181011_Leaders_34_7_E01.pepXML
No index list offset found. File will not be read.
WARNING: cannot open data file /content/181011_Leaders_34_7_E01.mzML in msms_run_summary tag... trying .mzXML ...
WARNING: CANNOT correct data file /content/181011_Leaders_34_7_E01.mzXML in msms_run_summary tag...
No index list offset found. File will not be read.
WARNING: cannot open data file /content/181011_Leaders_34_7_E01.mzML in msms_run_summary tag... trying .mzXML ...
WARNING: CANNOT correct data file /content/181011_Leaders_34_7_E01.mzXML in msms_run_summary tag...
 processed altogether 26774 results
INFO: Results written to file: /content/interact-181011_Leaders_34_7_E01.pep.xml
 file 1: /content/181011_Leaders_6_4_E04.pepXML
No index list offset found. File will not be read.
WARNING: cannot open data file /content/181011_Leaders_6_4_E04.mzML in msms_run_summary tag... trying .mzXML ...
WARNING: CANNOT correct data file /content/181011_Leaders_6_4_E04.mzXML in msms_run_summary tag...
No index list offset found. File will not be read.
WARNING: cannot open data file /content/181011_Leaders_6_4_E04.mzML in msms_run_summary tag... trying .mzXML ...
WARNING: CANNOT correct data file /content/181011_Leaders_6_4_E04.mzXML in msms_run_summary tag...
 processed altogether 21808 results
INFO: Results written to file: /content/interact-181011_Leaders_6_4_E04.pep.xml

  - /content/interact-181011_Leaders_11_4_E01.pep.xml
  - Building Commentz-Walter keyword tree...
  - Searching the tree...
  - Linking duplicate entries...
  - Printing results...

Using Decoy Label "rev_".
 (X! Tandem)
using search_offsets in mass mixture distr: 0
init with X! Tandem trypsin
MS Instrument info: Manufacturer: UNKNOWN, Model: UNKNOWN, Ionization: UNKNOWN, Analyzer: UNKNOWN, Detector: UNKNOWN

INFO: Processing standard MixtureModel ...
 PeptideProphet  (TPP v5.2.1-dev Flammagenitus, Build 201906251008-exported (Linux-x86_64)) AKeller@ISB
 read in 0 1+, 12618 2+, 10288 3+, 0 4+, 0 5+, 0 6+, and 0 7+ spectra.
Initialising statistical models ...
Found 0 Decoys, and 22906 Non-Decoys
WARNING: No decoys with label rev_ were found in this dataset. reverting to fully unsupervised method.
negmean = 0.0533258
negmean = 0.608781
negmean = 0.318186
negmean = -0.2
negmean = -0.2
negmean = -0.2
negmean = -0.2
Iterations: .........10.........20......
model complete after 27 iterations

  - /content/interact-181011_Leaders_34_7_E01.pep.xml
  - Building Commentz-Walter keyword tree...
  - Searching the tree...
  - Linking duplicate entries...
  - Printing results...

Using Decoy Label "rev_".
 (X! Tandem)
using search_offsets in mass mixture distr: 0
init with X! Tandem trypsin
MS Instrument info: Manufacturer: UNKNOWN, Model: UNKNOWN, Ionization: UNKNOWN, Analyzer: UNKNOWN, Detector: UNKNOWN

INFO: Processing standard MixtureModel ...
 PeptideProphet  (TPP v5.2.1-dev Flammagenitus, Build 201906251008-exported (Linux-x86_64)) AKeller@ISB
 read in 0 1+, 15161 2+, 11613 3+, 0 4+, 0 5+, 0 6+, and 0 7+ spectra.
Initialising statistical models ...
Found 0 Decoys, and 26774 Non-Decoys
WARNING: No decoys with label rev_ were found in this dataset. reverting to fully unsupervised method.
negmean = 0.0533258
negmean = 0.585461
negmean = 0.327574
negmean = -0.2
negmean = -0.2
negmean = -0.2
negmean = -0.2
Iterations: .........10.........20.......
model complete after 28 iterations

  - /content/interact-181011_Leaders_6_4_E04.pep.xml
  - Building Commentz-Walter keyword tree...
  - Searching the tree...
  - Linking duplicate entries...
  - Printing results...

Using Decoy Label "rev_".
 (X! Tandem)
using search_offsets in mass mixture distr: 0
init with X! Tandem trypsin
MS Instrument info: Manufacturer: UNKNOWN, Model: UNKNOWN, Ionization: UNKNOWN, Analyzer: UNKNOWN, Detector: UNKNOWN

INFO: Processing standard MixtureModel ...
 PeptideProphet  (TPP v5.2.1-dev Flammagenitus, Build 201906251008-exported (Linux-x86_64)) AKeller@ISB
 read in 0 1+, 12395 2+, 9413 3+, 0 4+, 0 5+, 0 6+, and 0 7+ spectra.
Initialising statistical models ...
Found 0 Decoys, and 21808 Non-Decoys
WARNING: No decoys with label rev_ were found in this dataset. reverting to fully unsupervised method.
negmean = 0.0533258
negmean = 0.581204
negmean = 0.310425
negmean = -0.2
negmean = -0.2
negmean = -0.2
negmean = -0.2
Iterations: .........10.........20......
model complete after 27 iterations
time="03:08:29" level=info msg=Done

In [ ]:
!./bin/micromamba run -n proteomics philosopher proteinprophet interact-*.pep.xml

time="03:08:29" level=info msg="Executing ProteinProphet  v5.1.2"
ProteinProphet (C++) by Insilicos LLC and LabKey Software, after the original Perl by A. Keller (TPP v6.0.0-rc15 Noctilucent, Build 202105021430-exported (Linux-x86_64))
 (no FPKM) (no groups) (using degen pep info)
Reading in /content/interact-181011_Leaders_11_4_E01.pep.xml...
...read in 0 1+, 6459 2+, 4755 3+, 0 4+, 0 5+, 0 6+, 0 7+ spectra with min prob 0.05

Reading in /content/interact-181011_Leaders_34_7_E01.pep.xml...
...read in 0 1+, 7425 2+, 5006 3+, 0 4+, 0 5+, 0 6+, 0 7+ spectra with min prob 0.05

Reading in /content/interact-181011_Leaders_6_4_E04.pep.xml...
...read in 0 1+, 6876 2+, 4696 3+, 0 4+, 0 5+, 0 6+, 0 7+ spectra with min prob 0.05

Initializing 14160 peptide weights: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Calculating protein lengths and molecular weights from database /content/human_swissprot.fasta
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........1000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........2000
.........:.........:.WARNING: Found the following zero-mass residues in protein entry sp|P07203|GPX1_HUMAN : U
MCAARLAAAAAAAQSVYAFSARPLAGGEPVSLGSLRGKVLLIENVASLUGTTVRDYTQMNELQRRLGPRGLVVLGFPCNQFGHQENAKNEEILNSLKYVRPGGGFEPNFMLFEKCEVNGAGAHPLFAFLREALPAPSDDATALMTDPKLITWSPVCRNDVAWNFEKFLVGPDGVPLRRYSRRFQTIDIEPDIEALLSQGPSCA
........:.........:.........:.........:.........:.........:.........:.........3000
.........:.........:WARNING: Found the following zero-mass residues in protein entry sp|P22352|GPX3_HUMAN : U
MARLLQASCLLSLLLAGFVSQSRGQEKSKMDCHGGISGTIYEYGALTIDGEEYIPFKQYAGKYVLFVNVASYUGLTGQYIELNALQEELAPFGLVILGFPCNQFGKQEPGENSEILPTLKYVRPGGGFVPNFQLFEKGDVNGEKEQKFYTFLKNSCPPTSELLGTSDRLFWEPMKVHDIRWNFEKFLVGPDGIPIMRWHHRTTVSNVKMDILSYMRRQAALGVKRK
.........:.........:.........:.........:.........:.........:.........:.........4000
.........:.........:.........:.......WARNING: Found the following zero-mass residues in protein entry sp|P49908|SEPP1_HUMAN : UUUUUUUUUU
MWRSLGLALALCLLPSGGTESQDQSSLCKQPPAWSIRDQDPMLNSNGSVTVVALLQASUYLCILQASKLEDLRVKLKKEGYSNISYIVVNHQGISSRLKYTHLKNKVSEHIPVYQQEENQTDVWTLLNGSKDDFLIYDRCGRLVYHLGLPFSFLTFPYVEEAIKIAYCEKKCGNCSLTTLKDEDFCKRVSLATVDKTVETPSPHYHHEHHHNHGHQHLGSSELSENQQPGAPNAPTHPAPPGLHHHHKHKGQHRQGHPENRDMPASEDLQDLQKKLCRKRCINQLLCKLPTDSELAPRSUCCHCRHLIFEKTGSAITUQCKENLPSLCSUQGLRAEENITESCQURLPPAAUQISQQLIPTEASASURUKNQAKKUEUPSN
..:.........:.........:.........:.........:.........:.........5000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........6000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........7000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........8000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........9000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........10000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........11000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........12000
.........:.........:.........:.........:.........:......WARNING: Found the following zero-mass residues in protein entry sp|Q9NNW7|TRXR2_HUMAN : U
MAAMAVALRGLGGRFRWRTQAVAGGVRGAARGAAAGQRDYDLLVVGGGSGGLACAKEAAQLGRKVAVVDYVEPSPQGTRWGLGGTCVNVGCIPKKLMHQAALLGGLIQDAPNYGWEVAQPVPHDWRKMAEAVQNHVKSLNWGHRVQLQDRKVKYFNIKASFVDEHTVCGVAKGGKEILLSADHIIIATGGRPRYPTHIEGALEYGITSDDIFWLKESPGKTLVVGASYVALECAGFLTGIGLDTTIMMRSIPLRGFDQQMSSMVIEHMASHGTRFLRGCAPSRVRRLPDGQLQVTWEDSTTGKEDTGTFDTVLWAIGRVPDTRSLNLEKAGVDTSPDTQKILVDSREATSVPHIYAIGDVVEGRPELTPIAIMAGRLLVQRLFGGSSDLMDYDNVPTTVFTPLEYGCVGLSEEEAVARHGQEHVEVYHAHYKPLEFTVAGRDASQCYVKMVCLREPPQLVLGLHFLGPNAGEVTQGFALGIKCGASYAQVMRTVGIHPTCSEEVVKLRISKRSGLDPTVTGCUG
...:.........:.........:.........:.........13000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........14000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........15000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........16000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........17000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........18000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........19000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........20000
.........:.........:.........:.........:..  Total: 20420
Computing degenerate peptides for 7551 proteins: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Computing probabilities for 7693 proteins.  Loop 1: 0%...20%...40%...60%...80%...100%  Loop 2: 0%...20%...40%...60%...80%...100%
Computing probabilities for 7693 proteins.  Loop 1: 0%...20%...40%...60%...80%...100%  Loop 2: 0%...20%...40%...60%...80%...100%
Computing probabilities for 7693 proteins.  Loop 1: 0%...20%...40%...60%...80%...100%  Loop 2: 0%...20%...40%...60%...80%...100%
Computing probabilities for 7693 proteins.  Loop 1: 0%...20%...40%...60%...80%...100%  Loop 2: 0%...20%...40%...60%...80%...100%
Calculating sensitivity...and error tables...
Computing MU for 7693 proteins: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
INFO: mu=0.000155597, db_size=22827080
time="03:08:31" level=info msg=Done

In [ ]:
!./bin/micromamba run -n proteomics philosopher filter \
  --pepxml interact-*.pep.xml \
  --psm 0.01 --pep 0.01 --prot 0.01

time="03:08:32" level=info msg="Executing Filter  v5.1.2"
time="03:08:32" level=info msg="Processing peptide identification files"
time="03:08:32" level=info msg="Parsing interact-181011_Leaders_11_4_E01.pep.xml"
time="03:08:32" level=info msg="1+ Charge profile" decoy=0 target=0
time="03:08:32" level=info msg="2+ Charge profile" decoy=0 target=6459
time="03:08:32" level=info msg="3+ Charge profile" decoy=0 target=4755
time="03:08:32" level=info msg="4+ Charge profile" decoy=0 target=0
time="03:08:32" level=info msg="5+ Charge profile" decoy=0 target=0
time="03:08:32" level=info msg="6+ Charge profile" decoy=0 target=0
time="03:08:32" level=info msg="Database search results" ions=5932 peptides=5507 psms=11214
time="03:08:32" level=info msg="Converged to 0.00 % FDR with 11214 PSMs" decoy=0 threshold=0.0501 total=11214
time="03:08:32" level=info msg="Converged to 0.00 % FDR with 5507 Peptides" decoy=0 threshold=0.0501 total=5507
time="03:08:32" level=info msg="Converged to 0.00 % FDR with 5932 Ions" decoy=0 threshold=0.0501 total=5932
time="03:08:32" level=info msg="Post processing identifications"
time="03:08:32" level=info msg="Assigning protein identifications to layers"
time="03:08:36" level=info msg="Final report numbers after FDR filtering, and post-processing" ions=5932 peptides=5507 proteins=0 psms=11214
time="03:08:36" level=info msg=Saving
time="03:08:36" level=info msg=Done

In [ ]:
!./bin/micromamba run -n proteomics philosopher report
!ls -lh psm.tsv peptide.tsv protein.tsv

time="03:08:36" level=info msg="Executing Report  v5.1.2"
time="03:08:36" level=info msg="Creating reports"
time="03:08:36" level=info msg=Done
ls: cannot access 'protein.tsv': No such file or directory
-rw-r--r-- 1 root root 926K Jan 21 03:08 peptide.tsv
-rw-r--r-- 1 root root 4.4M Jan 21 03:08 psm.tsv

##Proteomics Analysis Take #2
Proteins.tsv was missing, so I had to retry the process

In [ ]:
from pathlib import Path

in_fa  = Path("human_swissprot.fasta")
out_fa = Path("human_swissprot_targetdecoy.fasta")

#reverses sequences to make decoy for false positives
def make_target_decoy_fasta(in_path, out_path, decoy_prefix="rev_"):
  with open(in_path) as fin, open(out_path, "w") as fout:
    header, seq = None, []
    for line in fin:
      line = line.rstrip("\n")
      if line.startswith(">"):
        if header is not None:
          s = "".join(seq)
          # write target
          fout.write(header + "\n")
          for i in range(0, len(s), 60):
            fout.write(s[i:i+60] + "\n")
          # write decoy (reverse sequence)
          decoy_header = ">" + decoy_prefix + header[1:]
          ds = s[::-1]
          fout.write(decoy_header + "\n")
          for i in range(0, len(ds), 60):
            fout.write(ds[i:i+60] + "\n")
        header, seq = line, []
      else:
        seq.append(line.strip())

    # last entry
    if header is not None:
      s = "".join(seq)
      fout.write(header + "\n")
      for i in range(0, len(s), 60):
        fout.write(s[i:i+60] + "\n")
      decoy_header = ">" + decoy_prefix + header[1:]
      ds = s[::-1]
      fout.write(decoy_header + "\n")
      for i in range(0, len(ds), 60):
        fout.write(ds[i:i+60] + "\n")

make_target_decoy_fasta(in_fa, out_fa)
print("Wrote:", out_fa, "size:", out_fa.stat().st_size/1e6, "MB")

Wrote: human_swissprot_targetdecoy.fasta size: 27.413664 MB

In [ ]:
params = open("fragger.params").read().splitlines()
params = [line for line in params if not line.strip().startswith("database_name")]
params.insert(0, "database_name = human_swissprot_targetdecoy.fasta")
open("fragger.params","w").write("\n".join(params) + "\n")
!head -n 20 fragger.params

database_name = human_swissprot_targetdecoy.fasta
num_threads = 4

# Use ppm tolerance (required to avoid precursor_mass_units=2 error)
precursor_mass_units = 1
precursor_mass_lower = -20
precursor_mass_upper = 20

fragment_mass_units = 1
fragment_mass_tolerance = 20

search_enzyme_name = Trypsin
allowed_missed_cleavage = 2
variable_mod_01 = 15.9949 M
output_report_topN = 1

In [ ]:
import glob
msfragger_jar = sorted(glob.glob("/root/.local/share/mamba/envs/proteomics/share/msfragger-*/MSFragger-*/MSFragger-*.jar"))[-1]
KEY = "5c6f23ef-cadb78c8-8cfcf03e-aea9baf6"

!rm -f *.pepXML interact-*.pep.xml 2>/dev/null || true
!./bin/micromamba run -n proteomics java -Xmx16G -jar "{msfragger_jar}" --key {KEY} fragger.params *.mzML
!ls -lh *.pepXML

[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
MSFragger version MSFragger-4.2
Batmass-IO version 1.35.1
WARNING: A restricted method in java.lang.System has been called
WARNING: java.lang.System::load has been called by com.sun.jna.Native in an unnamed module (file:/root/.local/share/mamba/envs/proteomics/share/msfragger-4.2-0/MSFragger-4.2/MSFragger-4.2.jar)
WARNING: Use --enable-native-access=ALL-UNNAMED to avoid a warning for callers in this module
WARNING: Restricted methods will be blocked in a future release unless native access is enabled

timsdata library version timsdata-2-21-0-4
(c) University of Michigan
RawFileReader reading tool. Copyright (c) 2016 by Thermo Fisher Scientific, Inc. All rights reserved.
timdTOF .d reading tool. Copyright (c) 2022 by Bruker Daltonics GmbH & Co. KG. All rights reserved.
System OS: Linux, Architecture: amd64
Java Info: 25.0.1-internal, OpenJDK 64-Bit Server VM, Oracle Corporation
License key verified.
JVM started with 16 GB memory
Parameter 'data_type' was not supplied. Using default value: 0
Checking database...
Parameter 'num_enzyme_termini' was not supplied. Using default value: 2
Parameter 'search_enzyme_cutafter' was not supplied. Using default value: KR
Parameter 'search_enzyme_butnotafter' was not supplied. Using default value:
Parameter 'digest_min_length' was not supplied. Using default value: 7
Parameter 'digest_max_length' was not supplied. Using default value: 50
Parameter 'digest_mass_range' was not supplied. Using default value: 500.0 5000.0
Parameter 'delta_mass_exclude_ranges' was not supplied. Using default value: (-1.5, 3.5)
Parameter 'precursor_true_tolerance' was not supplied. Using default value: 20.000000
Parameter 'precursor_true_units' was not supplied. Using default value: 1
Parameter 'min_sequence_matches' was not supplied. Using default value: 2
Parameter 'remove_precursor_peak' was not supplied. Using default value: 1
Parameter 'intensity_transform' was not supplied. Using default value: 0
Parameter 'diagnostic_intensity_filter' was not supplied. Using default value: 0.000000
Parameter 'max_fragment_charge' was not supplied. Using default value: 2
Parameter 'deisotope' was not supplied. Using default value: 1
Parameter 'deneutralloss' was not supplied. Using default value: 1
Parameter 'use_topN_peaks' was not supplied. Using default value: 150
Parameter 'minimum_ratio' was not supplied. Using default value: 0.010000
Parameter 'clear_mz_range' was not supplied. Using default value: 0.0 0.0
Parameter 'minimum_peaks' was not supplied. Using default value: 15
Parameter 'min_fragments_modelling' was not supplied. Using default value: 2
Parameter 'min_matched_fragments' was not supplied. Using default value: 4
Parameter 'output_max_expect' was not supplied. Using default value: 50.000000
Parameter 'output_format' was not supplied. Using default value: pepxml
Parameter 'zero_bin_accept_expect' was not supplied. Using default value: 0.000000
Parameter 'zero_bin_mult_expect' was not supplied. Using default value: 1.000000
Parameter 'clip_nTerm_M' was not supplied. Using default value: 1
Parameter 'remove_precursor_range' was not supplied. Using default value: -1.5,1.5
Parameter 'precursor_mass_mode' was not supplied. Using default value: SELECTED
Parameter 'calibrate_mass' was not supplied. Using default value: 2
Parameter 'write_calibrated_mzml' was not supplied. Using default value: 0
Parameter 'write_mzbin_all' was not supplied. Using default value: 0
Parameter 'decoy_prefix' was not supplied. Using default value: rev_
Parameter 'use_all_mods_in_first_search' was not supplied. Using default value: 0
Parameter 'require_precursor' was not supplied. Using default value: 0
Parameter 'reuse_dia_fragment_peaks' was not supplied. Using default value: 0
Parameter 'activation_types' was not supplied. Using default value: all
Parameter 'analyzer_types' was not supplied. Using default value: all
Parameter 'fragment_ion_series' was not supplied. Using default value: b,y
Parameter 'ion_series_definitions' was not supplied. Using default value:
Parameter 'diagnostic_fragments' was not supplied. Using default value:
Checking spectral files...
181011_Leaders_11_4_E01.mzML: Scans = 53295; MS2 ITMS = false; MS2 FTMS = true; MS2 ASTMS = false; MS1 ITMS = false; Isolation sizes = [2.0]; Instrument = Q Exactive Plus
181011_Leaders_6_4_E04.mzML: Scans = 55526; MS2 ITMS = false; MS2 FTMS = true; MS2 ASTMS = false; MS1 ITMS = false; Isolation sizes = [2.0]; Instrument = Q Exactive Plus
181011_Leaders_34_7_E01.mzML: Scans = 58142; MS2 ITMS = false; MS2 FTMS = true; MS2 ASTMS = false; MS1 ITMS = false; Isolation sizes = [2.0]; Instrument = Q Exactive Plus
***********************************FIRST SEARCH************************************
Parameters:
num_threads = 4
database_name = human_swissprot_targetdecoy.fasta
decoy_prefix = rev_
precursor_mass_lower = -20.0
precursor_mass_upper = 20.0
precursor_mass_units = 1
data_type = 0
precursor_true_tolerance = 20.0
precursor_true_units = 1
fragment_mass_tolerance = 20.0
fragment_mass_units = 1
calibrate_mass = 2
use_all_mods_in_first_search = 0
write_calibrated_mzml = 0
write_uncalibrated_mzml = 1
write_mzbin_all = 0
isotope_error = 0/1
mass_offsets = 0
use_detailed_offsets = 0
labile_search_mode = OFF
restrict_deltamass_to = all
precursor_mass_mode = SELECTED
localize_delta_mass = 0
delta_mass_exclude_ranges = (-1.5, 3.5)
fragment_ion_series = b,y
ion_series_definitions =
search_enzyme_name = Trypsin
search_enzyme_sense_1 = C
search_enzyme_cut_1 = KR
search_enzyme_nocut_1 =
allowed_missed_cleavage_1 = 2
num_enzyme_termini = 2
clip_nTerm_M = 1
allow_multiple_variable_mods_on_residue = 0
max_variable_mods_per_peptide = 3
max_variable_mods_combinations = 5000
output_format = pepxml
output_report_topN = 1
output_max_expect = 50.0
report_alternative_proteins = 0
override_charge = 0
precursor_charge_low = 2
precursor_charge_high = 3
digest_min_length = 7
digest_max_length = 50
digest_mass_range_low = 500.0
digest_mass_range_high = 5000.0
max_fragment_charge = 1
deisotope = 1
deneutralloss = 1
track_zero_topN = 0
zero_bin_accept_expect = 0.0
zero_bin_mult_expect = 1.0
minimum_peaks = 15
use_topN_peaks = 150
minIonsScoring = 2
min_matched_fragments = 4
minimum_ratio = 0.01
intensity_transform = 0
activation_types = all
analyzer_types = all
group_variable = 0
require_precursor = 0
reuse_dia_fragment_peaks = 0
remove_precursor_peak = 1
remove_precursor_range = -1.5,1.5
clear_mz_range_low = 0.0
clear_mz_range_high = 0.0
excluded_scan_list_file =
mass_diff_to_variable_mod = 0
min_sequence_matches = 2
check_spectral_files = 1
variable_mod_01 = 15.9949 M
add_Cterm_peptide = 0.0
add_Cterm_protein = 0.0
add_Nterm_peptide = 0.0
add_Nterm_protein = 0.0
Number of unique peptides
	of length 7: 287794
	of length 8: 278875
	of length 9: 278147
	of length 10: 262685
	of length 11: 249280
	of length 12: 238556
	of length 13: 232374
	of length 14: 217775
	of length 15: 206490
	of length 16: 193025
	of length 17: 180696
	of length 18: 173473
	of length 19: 170471
	of length 20: 152441
	of length 21: 145879
	of length 22: 136775
	of length 23: 127571
	of length 24: 120951
	of length 25: 113888
	of length 26: 105915
	of length 27: 100932
	of length 28: 96389
	of length 29: 87647
	of length 30: 83199
	of length 31: 78018
	of length 32: 73969
	of length 33: 69161
	of length 34: 64722
	of length 35: 58720
	of length 36: 57011
	of length 37: 51997
	of length 38: 48856
	of length 39: 44020
	of length 40: 41942
	of length 41: 39063
	of length 42: 36024
	of length 43: 30222
	of length 44: 24515
	of length 45: 18750
	of length 46: 12312
	of length 47: 7741
	of length 48: 4480
	of length 49: 2435
	of length 50: 1484
In total 5006670 peptides.
Generated 7638880 modified peptides.
Number of peptides with more than 5000 modification patterns: 0
Selected fragment index width 0.10 Da.
311396196 fragments to be searched in 1 slices (2.90 GB total)
Operating on slice 1 of 1:
	Fragment index slice generated in 6.17 s
	001. 181011_Leaders_11_4_E01.mzML 8.1 s | deisotoping 0.4 s
		[progress: 53295/53295 (100%) - 17159 spectra/s] 3.1s
	002. 181011_Leaders_34_7_E01.mzML 7.2 s | deisotoping 0.2 s
		[progress: 58142/58142 (100%) - 22268 spectra/s] 2.6s
	003. 181011_Leaders_6_4_E04.mzML 6.6 s | deisotoping 0.1 s
		[progress: 55526/55526 (100%) - 27721 spectra/s] 2.0s
postprocessing 181011_Leaders_11_4_E01.mzML 0.3 s
postprocessing 181011_Leaders_34_7_E01.mzML 0.2 s
postprocessing 181011_Leaders_6_4_E04.mzML 0.2 s
***************************FIRST SEARCH DONE IN 1.004 MIN**************************

*********************MASS CALIBRATION AND PARAMETER OPTIMIZATION*******************
-----|---------------|---------------|---------------|---------------
     |  MS1   (Old)  |  MS1   (New)  |  MS2   (Old)  |  MS2   (New)
-----|---------------|---------------|---------------|---------------
 Run |  Median  MAD  |  Median  MAD  |  Median  MAD  |  Median  MAD
 001 |   0.76   1.46 |   0.03   0.69 |   0.31   2.59 |  -0.06   2.55
 002 |   0.52   1.41 |   0.02   0.76 |  -0.15   2.55 |  -0.10   2.54
 003 |  -0.74   1.42 |   0.05   0.65 |  -1.27   2.72 |  -0.03   2.71
-----|---------------|---------------|---------------|---------------
Finding the optimal parameters:
-------|-------|-------|-------|-------|-------|-------|-------|-------
  MS2  |    5  |    7  |   10  |   15  |   20  |   25  |   30  |   50
-------|-------|-------|-------|-------|-------|-------|-------|-------
 Count | skip  |   9772|  10026|  10130|  10108| skip rest
-------|-------|-------|-------|-------|-------|-------|-------|-------
-------|-------|-------|-------|-------|-------|-------
 Peaks | 300_0 | 200_0 | 175_0 | 150_1 | 125_1 | 100_1
-------|-------|-------|-------|-------|-------|-------
 Count |  10126|  10137|  10156|  10130| skip rest
-------|-------|-------|-------|-------|-------|-------
-------|-------
 Int.  |    1
-------|-------
 Count |  10174
-------|-------
-------|-------
 Rm P. |    0
-------|-------
 Count |  10209
-------|-------
New fragment_mass_tolerance = 15.000000 PPM
New use_topN_peaks = 175
New minimum_ratio = 0.000000
New intensity_transform = 1
New remove_precursor_peak = 0
************MASS CALIBRATION AND PARAMETER OPTIMIZATION DONE IN 2.278 MIN*********

************************************MAIN SEARCH************************************
Parameter 'data_type' was not supplied. Using default value: 0
Checking database...
Parameter 'num_enzyme_termini' was not supplied. Using default value: 2
Parameter 'search_enzyme_cutafter' was not supplied. Using default value: KR
Parameter 'search_enzyme_butnotafter' was not supplied. Using default value:
Parameter 'digest_min_length' was not supplied. Using default value: 7
Parameter 'digest_max_length' was not supplied. Using default value: 50
Parameter 'digest_mass_range' was not supplied. Using default value: 500.0 5000.0
Parameter 'localize_delta_mass' was not supplied. Using default value: 0
Parameter 'delta_mass_exclude_ranges' was not supplied. Using default value: (-1.5, 3.5)
Parameter 'precursor_true_tolerance' was not supplied. Using default value: 20.000000
Parameter 'precursor_true_units' was not supplied. Using default value: 1
Parameter 'mass_offsets' was not supplied. Using default value: 0
Parameter 'use_detailed_offsets' was not supplied. Using default value: 0
Parameter 'labile_search_mode' was not supplied. Using default value: OFF
Parameter 'restrict_deltamass_to' was not supplied. Using default value: all
Parameter 'min_sequence_matches' was not supplied. Using default value: 2
Parameter 'remove_precursor_peak' was not supplied. Using default value: 1
Parameter 'intensity_transform' was not supplied. Using default value: 0
Parameter 'diagnostic_intensity_filter' was not supplied. Using default value: 0.000000
Parameter 'max_fragment_charge' was not supplied. Using default value: 2
Parameter 'deisotope' was not supplied. Using default value: 1
Parameter 'deneutralloss' was not supplied. Using default value: 1
Parameter 'use_topN_peaks' was not supplied. Using default value: 150
Parameter 'minimum_ratio' was not supplied. Using default value: 0.010000
Parameter 'clear_mz_range' was not supplied. Using default value: 0.0 0.0
Parameter 'isotope_error' was not supplied. Using default value: 0
Parameter 'minimum_peaks' was not supplied. Using default value: 15
Parameter 'min_fragments_modelling' was not supplied. Using default value: 2
Parameter 'min_matched_fragments' was not supplied. Using default value: 4
Parameter 'override_charge' was not supplied. Using default value: 0
Parameter 'precursor_charge' was not supplied. Using default value: 1 4
Parameter 'output_max_expect' was not supplied. Using default value: 50.000000
Parameter 'output_format' was not supplied. Using default value: pepxml
Parameter 'track_zero_topN' was not supplied. Using default value: 0
Parameter 'zero_bin_accept_expect' was not supplied. Using default value: 0.000000
Parameter 'zero_bin_mult_expect' was not supplied. Using default value: 1.000000
Parameter 'allow_multiple_variable_mods_on_residue' was not supplied. Using default value: 0
Parameter 'max_variable_mods_per_peptide' was not supplied. Using default value: 3
Parameter 'max_variable_mods_combinations' was not supplied. Using default value: 5000
Parameter 'clip_nTerm_M' was not supplied. Using default value: 1
Parameter 'remove_precursor_range' was not supplied. Using default value: -1.5,1.5
Parameter 'precursor_mass_mode' was not supplied. Using default value: SELECTED
Parameter 'report_alternative_proteins' was not supplied. Using default value: 0
Parameter 'calibrate_mass' was not supplied. Using default value: 2
Parameter 'write_calibrated_mzml' was not supplied. Using default value: 0
Parameter 'write_mzbin_all' was not supplied. Using default value: 0
Parameter 'decoy_prefix' was not supplied. Using default value: rev_
Parameter 'use_all_mods_in_first_search' was not supplied. Using default value: 0
Parameter 'group_variable' was not supplied. Using default value: 0
Parameter 'require_precursor' was not supplied. Using default value: 0
Parameter 'reuse_dia_fragment_peaks' was not supplied. Using default value: 0
Parameter 'activation_types' was not supplied. Using default value: all
Parameter 'analyzer_types' was not supplied. Using default value: all
Parameter 'fragment_ion_series' was not supplied. Using default value: b,y
Parameter 'remainder_fragment_masses' was not supplied. Using default value:
Parameter 'Y_type_masses' was not supplied. Using default value:
Parameter 'ion_series_definitions' was not supplied. Using default value:
Parameter 'diagnostic_fragments' was not supplied. Using default value:
Parameter 'mass_diff_to_variable_mod' was not supplied. Using default value: 0
Parameters:
num_threads = 4
database_name = human_swissprot_targetdecoy.fasta
decoy_prefix = rev_
precursor_mass_lower = -20.0
precursor_mass_upper = 20.0
precursor_mass_units = 1
data_type = 0
precursor_true_tolerance = 20.0
precursor_true_units = 1
fragment_mass_tolerance = 15.0
fragment_mass_units = 1
calibrate_mass = 2
use_all_mods_in_first_search = 0
write_calibrated_mzml = 0
write_uncalibrated_mzml = 1
write_mzbin_all = 0
isotope_error = 0
mass_offsets = 0
use_detailed_offsets = 0
labile_search_mode = OFF
restrict_deltamass_to = all
precursor_mass_mode = SELECTED
localize_delta_mass = 0
delta_mass_exclude_ranges = (-1.5, 3.5)
fragment_ion_series = b,y
ion_series_definitions =
search_enzyme_name = Trypsin
search_enzyme_sense_1 = C
search_enzyme_cut_1 = KR
search_enzyme_nocut_1 =
allowed_missed_cleavage_1 = 2
num_enzyme_termini = 2
clip_nTerm_M = 1
allow_multiple_variable_mods_on_residue = 0
max_variable_mods_per_peptide = 3
max_variable_mods_combinations = 5000
output_format = pepxml
output_report_topN = 1
output_max_expect = 50.0
report_alternative_proteins = 0
override_charge = 0
precursor_charge_low = 1
precursor_charge_high = 4
digest_min_length = 7
digest_max_length = 50
digest_mass_range_low = 500.0
digest_mass_range_high = 5000.0
max_fragment_charge = 1
deisotope = 1
deneutralloss = 1
track_zero_topN = 0
zero_bin_accept_expect = 0.0
zero_bin_mult_expect = 1.0
minimum_peaks = 15
use_topN_peaks = 175
minIonsScoring = 2
min_matched_fragments = 4
minimum_ratio = 0.0
intensity_transform = 1
activation_types = all
analyzer_types = all
group_variable = 0
require_precursor = 0
reuse_dia_fragment_peaks = 0
remove_precursor_peak = 0
remove_precursor_range = -1.5,1.5
clear_mz_range_low = 0.0
clear_mz_range_high = 0.0
excluded_scan_list_file =
mass_diff_to_variable_mod = 0
min_sequence_matches = 2
check_spectral_files = 1
variable_mod_01 = 15.9949 M
add_Cterm_peptide = 0.0
add_Cterm_protein = 0.0
add_Nterm_peptide = 0.0
add_Nterm_protein = 0.0
Number of unique peptides
	of length 7: 287794
	of length 8: 278875
	of length 9: 278147
	of length 10: 262685
	of length 11: 249280
	of length 12: 238556
	of length 13: 232374
	of length 14: 217775
	of length 15: 206490
	of length 16: 193025
	of length 17: 180696
	of length 18: 173473
	of length 19: 170471
	of length 20: 152441
	of length 21: 145879
	of length 22: 136775
	of length 23: 127571
	of length 24: 120951
	of length 25: 113888
	of length 26: 105915
	of length 27: 100932
	of length 28: 96389
	of length 29: 87647
	of length 30: 83199
	of length 31: 78018
	of length 32: 73969
	of length 33: 69161
	of length 34: 64722
	of length 35: 58720
	of length 36: 57011
	of length 37: 51997
	of length 38: 48856
	of length 39: 44020
	of length 40: 41942
	of length 41: 39063
	of length 42: 36024
	of length 43: 30222
	of length 44: 24515
	of length 45: 18750
	of length 46: 12312
	of length 47: 7741
	of length 48: 4480
	of length 49: 2435
	of length 50: 1484
In total 5006670 peptides.
Generated 7638880 modified peptides.
Number of peptides with more than 5000 modification patterns: 0
Selected fragment index width 0.08 Da.
311396196 fragments to be searched in 1 slices (2.90 GB total)
Operating on slice 1 of 1:
	Fragment index slice generated in 5.72 s
	001. 181011_Leaders_11_4_E01.mzBIN_calibrated 0.1 s
		[progress: 53295/53295 (100%) - 29559 spectra/s] 1.8s
	002. 181011_Leaders_34_7_E01.mzBIN_calibrated 0.2 s
		[progress: 58142/58142 (100%) - 26356 spectra/s] 2.2s
	003. 181011_Leaders_6_4_E04.mzBIN_calibrated 0.1 s
		[progress: 55526/55526 (100%) - 34660 spectra/s] 1.6s
postprocessing 181011_Leaders_11_4_E01.mzBIN_calibrated 0.6 s
postprocessing 181011_Leaders_34_7_E01.mzBIN_calibrated 0.5 s
postprocessing 181011_Leaders_6_4_E04.mzBIN_calibrated 0.4 s
***************************MAIN SEARCH DONE IN 0.356 MIN***************************

*******************************TOTAL TIME 3.638 MIN********************************
-rw-r--r-- 1 root root 18M Jan 21 03:12 181011_Leaders_11_4_E01.pepXML
-rw-r--r-- 1 root root 22M Jan 21 03:12 181011_Leaders_34_7_E01.pepXML
-rw-r--r-- 1 root root 18M Jan 21 03:12 181011_Leaders_6_4_E04.pepXML

In [ ]:
!./bin/micromamba run -n proteomics philosopher peptideprophet --database human_swissprot_targetdecoy.fasta *.pepXML

time="03:12:16" level=info msg="Executing PeptideProphet  v5.1.2"
 file 1: /content/181011_Leaders_11_4_E01.pepXML
No index list offset found. File will not be read.
WARNING: cannot open data file /content/181011_Leaders_11_4_E01.mzML in msms_run_summary tag... trying .mzXML ...
WARNING: CANNOT correct data file /content/181011_Leaders_11_4_E01.mzXML in msms_run_summary tag...
No index list offset found. File will not be read.
WARNING: cannot open data file /content/181011_Leaders_11_4_E01.mzML in msms_run_summary tag... trying .mzXML ...
WARNING: CANNOT correct data file /content/181011_Leaders_11_4_E01.mzXML in msms_run_summary tag...
 processed altogether 19563 results
INFO: Results written to file: /content/interact-181011_Leaders_11_4_E01.pep.xml
 file 1: /content/181011_Leaders_34_7_E01.pepXML
No index list offset found. File will not be read.
WARNING: cannot open data file /content/181011_Leaders_34_7_E01.mzML in msms_run_summary tag... trying .mzXML ...
WARNING: CANNOT correct data file /content/181011_Leaders_34_7_E01.mzXML in msms_run_summary tag...
No index list offset found. File will not be read.
WARNING: cannot open data file /content/181011_Leaders_34_7_E01.mzML in msms_run_summary tag... trying .mzXML ...
WARNING: CANNOT correct data file /content/181011_Leaders_34_7_E01.mzXML in msms_run_summary tag...
 processed altogether 23464 results
INFO: Results written to file: /content/interact-181011_Leaders_34_7_E01.pep.xml
 file 1: /content/181011_Leaders_6_4_E04.pepXML
No index list offset found. File will not be read.
WARNING: cannot open data file /content/181011_Leaders_6_4_E04.mzML in msms_run_summary tag... trying .mzXML ...
WARNING: CANNOT correct data file /content/181011_Leaders_6_4_E04.mzXML in msms_run_summary tag...
No index list offset found. File will not be read.
WARNING: cannot open data file /content/181011_Leaders_6_4_E04.mzML in msms_run_summary tag... trying .mzXML ...
WARNING: CANNOT correct data file /content/181011_Leaders_6_4_E04.mzXML in msms_run_summary tag...
 processed altogether 19054 results
INFO: Results written to file: /content/interact-181011_Leaders_6_4_E04.pep.xml

  - /content/interact-181011_Leaders_11_4_E01.pep.xml
  - Building Commentz-Walter keyword tree...
  - Searching the tree...
  - Linking duplicate entries...
  - Printing results...

Using Decoy Label "rev_".
 (X! Tandem)
using search_offsets in mass mixture distr: 0
init with X! Tandem trypsin
MS Instrument info: Manufacturer: UNKNOWN, Model: UNKNOWN, Ionization: UNKNOWN, Analyzer: UNKNOWN, Detector: UNKNOWN

INFO: Processing standard MixtureModel ...
 PeptideProphet  (TPP v5.2.1-dev Flammagenitus, Build 201906251008-exported (Linux-x86_64)) AKeller@ISB
 read in 0 1+, 11236 2+, 8327 3+, 0 4+, 0 5+, 0 6+, and 0 7+ spectra.
Initialising statistical models ...
Found 6293 Decoys, and 13270 Non-Decoys
Iterations: .........10.........20.....
model complete after 26 iterations

  - /content/interact-181011_Leaders_34_7_E01.pep.xml
  - Building Commentz-Walter keyword tree...
  - Searching the tree...
  - Linking duplicate entries...
  - Printing results...

Using Decoy Label "rev_".
 (X! Tandem)
using search_offsets in mass mixture distr: 0
init with X! Tandem trypsin
MS Instrument info: Manufacturer: UNKNOWN, Model: UNKNOWN, Ionization: UNKNOWN, Analyzer: UNKNOWN, Detector: UNKNOWN

INFO: Processing standard MixtureModel ...
 PeptideProphet  (TPP v5.2.1-dev Flammagenitus, Build 201906251008-exported (Linux-x86_64)) AKeller@ISB
 read in 0 1+, 13955 2+, 9509 3+, 0 4+, 0 5+, 0 6+, and 0 7+ spectra.
Initialising statistical models ...
Found 7815 Decoys, and 15649 Non-Decoys
Iterations: .........10.........20.....
model complete after 26 iterations

  - /content/interact-181011_Leaders_6_4_E04.pep.xml
  - Building Commentz-Walter keyword tree...
  - Searching the tree...
  - Linking duplicate entries...
  - Printing results...

Using Decoy Label "rev_".
 (X! Tandem)
using search_offsets in mass mixture distr: 0
init with X! Tandem trypsin
MS Instrument info: Manufacturer: UNKNOWN, Model: UNKNOWN, Ionization: UNKNOWN, Analyzer: UNKNOWN, Detector: UNKNOWN

INFO: Processing standard MixtureModel ...
 PeptideProphet  (TPP v5.2.1-dev Flammagenitus, Build 201906251008-exported (Linux-x86_64)) AKeller@ISB
 read in 0 1+, 11261 2+, 7793 3+, 0 4+, 0 5+, 0 6+, and 0 7+ spectra.
Initialising statistical models ...
Found 5863 Decoys, and 13191 Non-Decoys
Iterations: .........10.........20....
model complete after 25 iterations
time="03:12:36" level=info msg=Done

In [ ]:
!./bin/micromamba run -n proteomics philosopher proteinprophet interact-*.pep.xml

time="03:12:36" level=info msg="Executing ProteinProphet  v5.1.2"
ProteinProphet (C++) by Insilicos LLC and LabKey Software, after the original Perl by A. Keller (TPP v6.0.0-rc15 Noctilucent, Build 202105021430-exported (Linux-x86_64))
 (no FPKM) (no groups) (using degen pep info)
Reading in /content/interact-181011_Leaders_11_4_E01.pep.xml...
...read in 0 1+, 4707 2+, 3114 3+, 0 4+, 0 5+, 0 6+, 0 7+ spectra with min prob 0.05

Reading in /content/interact-181011_Leaders_34_7_E01.pep.xml...
...read in 0 1+, 5905 2+, 3138 3+, 0 4+, 0 5+, 0 6+, 0 7+ spectra with min prob 0.05

Reading in /content/interact-181011_Leaders_6_4_E04.pep.xml...
...read in 0 1+, 5085 2+, 3177 3+, 0 4+, 0 5+, 0 6+, 0 7+ spectra with min prob 0.05

Initializing 6312 peptide weights: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Calculating protein lengths and molecular weights from database /content/human_swissprot_targetdecoy.fasta
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........1000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........2000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........3000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........4000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........5000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........6000
.........:.........:.........:.........:WARNING: Found the following zero-mass residues in protein entry sp|P22352|GPX3_HUMAN : U
MARLLQASCLLSLLLAGFVSQSRGQEKSKMDCHGGISGTIYEYGALTIDGEEYIPFKQYAGKYVLFVNVASYUGLTGQYIELNALQEELAPFGLVILGFPCNQFGKQEPGENSEILPTLKYVRPGGGFVPNFQLFEKGDVNGEKEQKFYTFLKNSCPPTSELLGTSDRLFWEPMKVHDIRWNFEKFLVGPDGIPIMRWHHRTTVSNVKMDILSYMRRQAALGVKRK
.........:.........:.........:.........:.........:.........7000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........8000
.........:.........:.........:.........:.........:.........:.........:....WARNING: Found the following zero-mass residues in protein entry sp|P49908|SEPP1_HUMAN : UUUUUUUUUU
MWRSLGLALALCLLPSGGTESQDQSSLCKQPPAWSIRDQDPMLNSNGSVTVVALLQASUYLCILQASKLEDLRVKLKKEGYSNISYIVVNHQGISSRLKYTHLKNKVSEHIPVYQQEENQTDVWTLLNGSKDDFLIYDRCGRLVYHLGLPFSFLTFPYVEEAIKIAYCEKKCGNCSLTTLKDEDFCKRVSLATVDKTVETPSPHYHHEHHHNHGHQHLGSSELSENQQPGAPNAPTHPAPPGLHHHHKHKGQHRQGHPENRDMPASEDLQDLQKKLCRKRCINQLLCKLPTDSELAPRSUCCHCRHLIFEKTGSAITUQCKENLPSLCSUQGLRAEENITESCQURLPPAAUQISQQLIPTEASASURUKNQAKKUEUPSN
.....:.........:.........9000
.........:.........:.........:.........:..WARNING: Found the following zero-mass residues in protein entry sp|P55073|IOD3_HUMAN : U
MPRQATSRLVVGEGEGSQGASGPAATMLRSLLLHSLRLCAQTASCLVLFPRFLGTAFMLWLLDFLCIRKHFLGRRRRGQPEPEVELNSEGEEVPPDDPPICVSDDNRLCTLASLKAVWHGQKLDFFKQAHEGGPAPNSEVVLPDGFQSQHILDYAQGNRPLVLNFGSCTUPPFMARMSAFQRLVTKYQRDVDFLIIYIEEAHPSDGWVTTDSPYIIPQHRSLEDRVSAARVLQQGAPGCALVLDTMANSSSSAYGAYFERLYVIQSGTIMYQGGRGPDGYQVSELRTWLERYDEQLHGARPRRV
.......:.........:.........:.........:.........:.........10000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........11000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........12000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........13000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........14000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........15000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........16000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........17000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........18000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........19000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........20000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........21000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........22000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........23000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........24000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........25000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........26000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........27000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........28000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........29000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........30000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........31000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........32000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........33000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........34000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........35000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........36000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........37000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........38000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........39000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........40000
.........:.........:.........:.........:.........:.........:.........:.........:....  Total: 40840
Computing degenerate peptides for 3217 proteins: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Computing probabilities for 3321 proteins.  Loop 1: 0%...20%...40%...60%...80%...100%  Loop 2: 0%...20%...40%...60%...80%...100%
Computing probabilities for 3321 proteins.  Loop 1: 0%...20%...40%...60%...80%...100%  Loop 2: 0%...20%...40%...60%...80%...100%
Computing probabilities for 3321 proteins.  Loop 1: 0%...20%...40%...60%...80%...100%  Loop 2: 0%...20%...40%...60%...80%...100%
Computing probabilities for 3321 proteins.  Loop 1: 0%...20%...40%...60%...80%...100%  Loop 2: 0%...20%...40%...60%...80%...100%
Computing probabilities for 3321 proteins.  Loop 1: 0%...20%...40%...60%...80%...100%  Loop 2: 0%...20%...40%...60%...80%...100%
Calculating sensitivity...and error tables...
Computing MU for 3321 proteins: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
INFO: mu=4.34848e-05, db_size=45654254
time="03:12:38" level=info msg=Done

In [ ]:
!./bin/micromamba run -n proteomics philosopher filter --pepxml interact-*.pep.xml --psm 0.01 --pep 0.01 --prot 0.01
!./bin/micromamba run -n proteomics philosopher report
!ls -lh psm.tsv peptide.tsv protein.tsv

time="03:12:38" level=info msg="Executing Filter  v5.1.2"
time="03:12:38" level=info msg="Processing peptide identification files"
time="03:12:38" level=info msg="Parsing interact-181011_Leaders_11_4_E01.pep.xml"
time="03:12:39" level=info msg="1+ Charge profile" decoy=0 target=0
time="03:12:39" level=info msg="2+ Charge profile" decoy=0 target=4708
time="03:12:39" level=info msg="3+ Charge profile" decoy=0 target=3114
time="03:12:39" level=info msg="4+ Charge profile" decoy=0 target=0
time="03:12:39" level=info msg="5+ Charge profile" decoy=0 target=0
time="03:12:39" level=info msg="6+ Charge profile" decoy=0 target=0
time="03:12:39" level=info msg="Database search results" ions=3078 peptides=2702 psms=7822
time="03:12:39" level=info msg="Converged to 0.00 % FDR with 7821 PSMs" decoy=0 threshold=0.0501 total=7821
time="03:12:39" level=info msg="Converged to 0.00 % FDR with 2701 Peptides" decoy=0 threshold=0.0501 total=2701
time="03:12:39" level=info msg="Converged to 0.00 % FDR with 3077 Ions" decoy=0 threshold=0.0501 total=3077
time="03:12:39" level=info msg="Post processing identifications"
time="03:12:39" level=info msg="Assigning protein identifications to layers"
time="03:12:41" level=info msg="Final report numbers after FDR filtering, and post-processing" ions=3077 peptides=2701 proteins=0 psms=7821
time="03:12:41" level=info msg=Saving
time="03:12:41" level=info msg=Done
time="03:12:41" level=info msg="Executing Report  v5.1.2"
time="03:12:41" level=info msg="Creating reports"
time="03:12:41" level=info msg=Done
ls: cannot access 'protein.tsv': No such file or directory
-rw-r--r-- 1 root root 435K Jan 21 03:12 peptide.tsv
-rw-r--r-- 1 root root 3.0M Jan 21 03:12 psm.tsv

In [ ]:
!ls -lh *.prot.xml *.protXML 2>/dev/null || true
!ls -lh interact*.prot* 2>/dev/null || true

-rw-r--r-- 1 root root 4.7M Jan 21 03:12  interact.prot.xml
-rw-r--r-- 1 root root 4.7M Jan 21 03:12 interact.prot.xml

In [ ]:
!./bin/micromamba run -n proteomics philosopher filter \
  --pepxml interact-*.pep.xml \
  --protxml interact.prot.xml \
  --psm 0.01 --pep 0.01 --prot 0.01

time="03:12:42" level=info msg="Executing Filter  v5.1.2"
time="03:12:42" level=info msg="Processing peptide identification files"
time="03:12:42" level=info msg="Parsing interact-181011_Leaders_11_4_E01.pep.xml"
time="03:12:42" level=info msg="1+ Charge profile" decoy=0 target=0
time="03:12:42" level=info msg="2+ Charge profile" decoy=0 target=4708
time="03:12:42" level=info msg="3+ Charge profile" decoy=0 target=3114
time="03:12:42" level=info msg="4+ Charge profile" decoy=0 target=0
time="03:12:42" level=info msg="5+ Charge profile" decoy=0 target=0
time="03:12:42" level=info msg="6+ Charge profile" decoy=0 target=0
time="03:12:42" level=info msg="Database search results" ions=3078 peptides=2702 psms=7822
time="03:12:42" level=info msg="Converged to 0.00 % FDR with 7821 PSMs" decoy=0 threshold=0.0501 total=7821
time="03:12:42" level=info msg="Converged to 0.00 % FDR with 2701 Peptides" decoy=0 threshold=0.0501 total=2701
time="03:12:42" level=info msg="Converged to 0.00 % FDR with 3077 Ions" decoy=0 threshold=0.0501 total=3077
time="03:12:42" level=info msg="Protein inference results" decoy=29 target=3018
time="03:12:42" level=info msg="Converged to 0.94 % FDR with 1589 Proteins" decoy=15 threshold=0.502 total=1604
time="03:12:43" level=info msg="2D FDR estimation: Protein mirror image" decoy=1589 target=1589
time="03:12:43" level=info msg="Second filtering results" ions=2499 peptides=2125 psms=7207
time="03:12:43" level=info msg="Converged to 0.00 % FDR with 7206 PSMs" decoy=0 threshold=0.0524 total=7206
time="03:12:43" level=info msg="Converged to 0.00 % FDR with 2124 Peptides" decoy=0 threshold=0.0524 total=2124
time="03:12:43" level=info msg="Converged to 0.00 % FDR with 2498 Ions" decoy=0 threshold=0.0524 total=2498
time="03:12:43" level=info msg="Post processing identifications"
time="03:12:43" level=info msg="Assigning protein identifications to layers"
time="03:12:45" level=info msg="Processing protein inference"
time="03:12:45" level=info msg="Synchronizing PSMs and proteins"
time="03:12:45" level=info msg="Final report numbers after FDR filtering, and post-processing" ions=2496 peptides=2122 proteins=804 psms=7204
time="03:12:45" level=info msg=Saving
time="03:12:45" level=info msg=Done

In [ ]:
!./bin/micromamba run -n proteomics philosopher report
!ls -lh psm.tsv peptide.tsv protein.tsv

time="03:12:45" level=info msg="Executing Report  v5.1.2"
time="03:12:45" level=info msg="Creating reports"
time="03:12:45" level=info msg=Done
-rw-r--r-- 1 root root 335K Jan 21 03:12 peptide.tsv
-rw-r--r-- 1 root root 177K Jan 21 03:12 protein.tsv
-rw-r--r-- 1 root root 2.8M Jan 21 03:12 psm.tsv

##Proteomics Analysis

In [ ]:
import pandas as pd

#analyzes all proteins and their total count - sees which one has the greatest intensities
prot = pd.read_csv("protein.tsv", sep="\t")

id_col = next((c for c in prot.columns if "protein" in c.lower() or "accession" in c.lower()), prot.columns[0])
count_col = next((c for c in prot.columns if "psm" in c.lower() or "spectral" in c.lower()), None)

print("ID:", id_col)
print("COUNT:", count_col)

top = prot.sort_values(count_col, ascending=False).head(30)[[id_col, count_col]]
display(top)

ID: Protein
COUNT: Total Spectral Count

                   Protein  Total Spectral Count
73    sp|P04114|APOB_HUMAN                   647
30     sp|P01024|CO3_HUMAN                   605
27    sp|P01011|AACT_HUMAN                   405
143  sp|P19827|ITIH1_HUMAN                   363
11    sp|P00450|CERU_HUMAN                   297
25    sp|P01008|ANT3_HUMAN                   264
113   sp|P0C0L4|CO4A_HUMAN                   241
114   sp|P0C0L5|CO4B_HUMAN                   232
208  sp|Q14624|ITIH4_HUMAN                   219
52    sp|P02751|FINC_HUMAN                   202
62    sp|P02787|TRFE_HUMAN                   170
142  sp|P19823|ITIH2_HUMAN                   149
53    sp|P02753|RET4_HUMAN                   129
31     sp|P01031|CO5_HUMAN                   120
108   sp|P08697|A2AP_HUMAN                   106
29    sp|P01023|A2MG_HUMAN                   104
64    sp|P02790|HEMO_HUMAN                   102
107   sp|P08603|CFAH_HUMAN                   100
197  sp|Q06033|ITIH3_HUMAN                    90
59    sp|P02774|VTDB_HUMAN                    87
89    sp|P06396|GELS_HUMAN                    82
37   sp|P02647|APOA1_HUMAN                    59
54    sp|P02760|AMBP_HUMAN                    57
26    sp|P01009|A1AT_HUMAN                    56
22    sp|P00751|CFAB_HUMAN                    56
177   sp|P43652|AFAM_HUMAN                    55
85    sp|P05543|THBG_HUMAN                    53
86    sp|P05546|HEP2_HUMAN                    49
100   sp|P07360|CO8G_HUMAN                    48
98    sp|P07358|CO8B_HUMAN                    47

In [ ]:
import pandas as pd

#analyzes all peptides and their total count - sees which one has the greatest intensities
pep = pd.read_csv("peptide.tsv", sep="\t")

pep_col = next((c for c in pep.columns if "peptide" in c.lower() or "sequence" in c.lower()), pep.columns[0])
count_col = next((c for c in pep.columns if "psm" in c.lower() or "count" in c.lower()), None)

top_peptides = pep.sort_values(count_col, ascending=False).head(30)
display(top_peptides[[pep_col, count_col]])

                                     Peptide  Spectral Count
33                   AFLEVNEEGSEAAASTAVVIAGR             186
827                     HYYIGIIETTWDYASDHGEK             130
955            KDPEGLFLQDNIVAEFSVDETGQMSATAK             125
1226                      LYGSEAFATDFQDSAAAK             111
146                      AVLDVFEEGTEASAATAVK             107
1683                   TAFISDFAVTADGNAFIGDIK             106
733                    GTHVDLGLASANVDFAFSLYK             101
62    AIAANEADAVTLDAGLVYDAYLAPNNLKPVVAEFYGSK              90
192                    DFSAEYEEDGKYEGLQEWEGK              72
486                             EVVADSVWVDVK              67
995                       KVEGTAFVIFGIQDGEQR              66
1035                LELELRPTGEIEQYSVSATYELQR              56
1559                  SGVQMNTNFFHESGLEAHVALK              54
670    GISEQSLVVSGVQHQSTLELSEVGVEAAAATSIAMSR              54
1608                   SLYVSATVILHSGSDMVQAER              52
1966                          VTDATETTITISWR              52
1799                   TTLTAFGFASADLIEIGLEGK              51
1640                    SSIDIENGFISESQYTYALK              51
279                         DSITTWEILAVSMSDK              50
1873                   VGLSGMAIADVTLLSGFHALR              49
467                          ETAVDGELVVLYDVK              46
326                            EDFTSLSLVLYSR              46
587                          FVTVQATFGTQVVEK              45
362                   EFVVMFSVVDENFSWYLEDNIK              44
1332                        NMEQFQVSVSVAPNAK              43
1273                 MTVSTLVLGEGATEAEISMTSTR              42
1969                            VTFQLTYEEVLK              40
602                   GAVHVVVAETDYQSFAVLYLER              39
1044       LEVANMQAELVAKPSVSVEFVTNMGIIIPDFAR              39
1970                           VTFQLTYEEVLKR              38

In [ ]:
import pandas as pd
prot = pd.read_csv("protein.tsv", sep="\t")
prot.head()

,Protein,Protein ID,Entry Name,Gene,Length,Is Decoy,Is Contaminant,Organism,Protein Description,Protein Existence,...,Razor Peptides,Total Spectral Count,Unique Spectral Count,Razor Spectral Count,Total Intensity,Unique Intensity,Razor Intensity,Razor Assigned Modifications,Razor Observed Modifications,Indistinguishable Proteins
0,sp|A0A0C4DH38|HV551_HUMAN,A0A0C4DH38,HV551_HUMAN,IGHV5-51,117,False,False,Homo sapiens,Immunoglobulin heavy variable 5-51,1:Experimental evidence at protein level,...,0,5,5,0,0,0,0,NaN,NaN,NaN
1,sp|O00151|PDLI1_HUMAN,O00151,PDLI1_HUMAN,PDLIM1,329,False,False,Homo sapiens,PDZ and LIM domain protein 1,1:Experimental evidence at protein level,...,0,1,1,0,0,0,0,NaN,NaN,NaN
2,sp|O00391|QSOX1_HUMAN,O00391,QSOX1_HUMAN,QSOX1,747,False,False,Homo sapiens,Sulfhydryl oxidase 1,1:Experimental evidence at protein level,...,0,8,8,0,0,0,0,NaN,NaN,NaN
3,sp|O00533|NCHL1_HUMAN,O00533,NCHL1_HUMAN,CHL1,1208,False,False,Homo sapiens,Neural cell adhesion molecule L1-like protein,1:Experimental evidence at protein level,...,0,3,3,0,0,0,0,NaN,NaN,NaN
4,sp|O14786|NRP1_HUMAN,O14786,NRP1_HUMAN,NRP1,923,False,False,Homo sapiens,Neuropilin-1,1:Experimental evidence at protein level,...,0,6,6,0,0,0,0,NaN,NaN,NaN

Warning: Total number of columns (26) exceeds max_columns (20) limiting to first (20) columns.

In [ ]:
print(prot.columns.tolist())

['Protein', 'Protein ID', 'Entry Name', 'Gene', 'Length', 'Is Decoy', 'Is Contaminant', 'Organism', 'Protein Description', 'Protein Existence', 'Coverage', 'Protein Probability', 'Top Peptide Probability', 'Protein Qvalue', 'Total Peptides', 'Unique Peptides', 'Razor Peptides', 'Total Spectral Count', 'Unique Spectral Count', 'Razor Spectral Count', 'Total Intensity', 'Unique Intensity', 'Razor Intensity', 'Razor Assigned Modifications', 'Razor Observed Modifications', 'Indistinguishable Proteins']

In [ ]:
import pandas as pd

prot = pd.read_csv("protein.tsv", sep="\t")

# Keep only real human proteins, gets rid of decoys
prot_filt = prot[
  (prot["Is Decoy"] == False) &
  (prot["Is Contaminant"] == False) &
  (prot["Organism"].str.contains("Homo sapiens", na=False))
]

In [ ]:
prot_filt["ProminenceScore"] = (
  prot_filt["Unique Peptides"] * 2 +
  prot_filt["Unique Spectral Count"] +
  prot_filt["Unique Intensity"] / prot_filt["Unique Intensity"].max() * 10
)

In [ ]:
top15 = prot_filt.sort_values(by=["Protein Probability", "ProminenceScore", "Unique Peptides"], ascending=[False, False, False]).head(15)

top15[[
  "Protein ID", "Entry Name", "Gene",
  "Protein Description",
  "Unique Peptides", "Unique Spectral Count",
  "Unique Intensity", "Coverage",
  "Protein Probability", "Protein Qvalue",
  "ProminenceScore"
]]

,Protein ID,Entry Name,Gene,Protein Description,Unique Peptides,Unique Spectral Count,Unique Intensity,Coverage,Protein Probability,Protein Qvalue,ProminenceScore
73,P04114,APOB_HUMAN,APOB,Apolipoprotein B-100,123,647,0,35.00,1.0,0.0,NaN
30,P01024,CO3_HUMAN,C3,Complement C3,66,604,0,54.24,1.0,0.0,NaN
52,P02751,FINC_HUMAN,FN1,Fibronectin,45,202,0,30.16,1.0,0.0,NaN
208,Q14624,ITIH4_HUMAN,ITIH4,Inter-alpha-trypsin inhibitor heavy chain H4,34,216,0,48.06,1.0,0.0,NaN
11,P00450,CERU_HUMAN,CP,Ceruloplasmin,32,297,0,40.75,1.0,0.0,NaN
142,P19823,ITIH2_HUMAN,ITIH2,Inter-alpha-trypsin inhibitor heavy chain H2,29,148,0,41.12,1.0,0.0,NaN
31,P01031,CO5_HUMAN,C5,Complement C5,28,119,0,27.21,1.0,0.0,NaN
143,P19827,ITIH1_HUMAN,ITIH1,Inter-alpha-trypsin inhibitor heavy chain H1,26,363,0,42.48,1.0,0.0,NaN
29,P01023,A2MG_HUMAN,A2M,Alpha-2-macroglobulin,25,100,0,31.82,1.0,0.0,NaN
25,P01008,ANT3_HUMAN,SERPINC1,Antithrombin-III,19,264,0,44.18,1.0,0.0,NaN
22,P00751,CFAB_HUMAN,CFB,Complement factor B,18,56,0,25.39,1.0,0.0,NaN
37,P02647,APOA1_HUMAN,APOA1,Apolipoprotein A-I,18,57,0,61.42,1.0,0.0,NaN
27,P01011,AACT_HUMAN,SERPINA3,Alpha-1-antichymotrypsin,17,397,0,48.70,1.0,0.0,NaN
126,P12259,FA5_HUMAN,F5,Coagulation factor V,17,25,0,10.52,1.0,0.0,NaN
89,P06396,GELS_HUMAN,GSN,Gelsolin,16,81,0,38.49,1.0,0.0,NaN

In [ ]:
#top protein contributors to MDD
top15[["Gene", "Protein Description"]]

         Gene                           Protein Description
73       APOB                          Apolipoprotein B-100
30         C3                                 Complement C3
52        FN1                                   Fibronectin
208     ITIH4  Inter-alpha-trypsin inhibitor heavy chain H4
11         CP                                 Ceruloplasmin
142     ITIH2  Inter-alpha-trypsin inhibitor heavy chain H2
31         C5                                 Complement C5
143     ITIH1  Inter-alpha-trypsin inhibitor heavy chain H1
29        A2M                         Alpha-2-macroglobulin
25   SERPINC1                              Antithrombin-III
22        CFB                           Complement factor B
37      APOA1                            Apolipoprotein A-I
27   SERPINA3                      Alpha-1-antichymotrypsin
126        F5                          Coagulation factor V
89        GSN                                      Gelsolin